### ISSUE TITLE
Minor errors running latest S5

### ISSUE THREAD

**Issue by cpiaulet** [kevin218/Eureka#126]
Since merging the latest edits and re-running S5, I have noticed several things that I want to flag for others if that can help:
- my S4 outputs obtained with the previous version of the code were not compatible with the new S5 read-in (there was stuff missing in the S4 meta file). I had to re-run S4, then S5 worked fine -> just be aware that S5 is not reverse-compatible with previously-generated S4 outputs
- the template S5 ecf file for parameters would require the `time_offset ` parameter to be specified (even if it is zero), otherwise I get an error.
For me, it was only a matter of adding one line to the params ecf file. It is a very minor edit which I will include in my next pull request if needed, but it might help others if you run into this error! Another option would be to set it to zero by default if it is not specified in the params file.

**Comment by cpiaulet** [comment]
another minor issue (now fixed in my code, will be fixed in my next pull request): the plots for the results from the light-curve fitting did not have the specified time offset correctly printing in the xlabel.

**Comment by taylorbell57** [comment]
1. Yeah, unfortunately I had to make some edits to the inputs and outputs of some of the stages that broke backwards compatibility. I tried to get those merged ASAP so that it causes as little trouble for people with the data challenge, and hopefully the I/O from each stage will be more stable (although it will be more variable near the edges, aka S1-S2 and S5-S6).
2. Indeed, I forgot to include that in the S5 template and it is fixed in my currently under review PR #122 
3. Hah, indeed - I hadn't even noticed that one! Good catch!
