### ISSUE TITLE
[Bug]: Github file error when pulling from main branch

### ISSUE THREAD

**Issue by evamariaa** [kevin218/Eureka#291]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

When fetching upstream from main branch to my forked repository using the Github desktop app, I get an error regarding a file in the tests/data/WFC3 (see below) folder. 

### Error traceback output

error: invalid path 'tests/data/WFC3/cal/leapdir/leap-seconds.3881174400?'
Updating d479abe..b4d1844

### What operating system are you using?

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
So this was just on fetching? This file is a reference file for WFC3 testing code - I'm surprised it could cause an issue. Maybe it's that it doesn't have an acceptable file extension for Windows?

**Comment by taylorbell57** [comment]
Oh wait, the issue is almost 100% because the filename ends in a question mark which the windows filesystem will get really angry about. Let me try to edit how that file gets saved to avoid that headache for Windows users. Out of curiosity, do you normally use windows for eureka? I was wondering how well Windows might work with Eureka

**Comment by evamariaa** [comment]
Ah I see. I assumed it was a Windows problem haha. Thanks so much!
I don't use Windows for Eureka! so can't comment sorry! I run Eureka! on the clusters at Warwick, but I don't like using Github on the terminal when it comes to looking at big commits and file changes, the Github desktop app better for visualising.
