### ISSUE TITLE
questions about `chromatic` readers for `Eureka!`

### ISSUE THREAD

**Issue by zkbt** [kevin218/Eureka#360]
### What happened?

Hi lovely Eureka! folks,

I've update the Eureka! readers for [chromatic](https://zkbt.github.io/chromatic/), incorporating the new(-ish?) hdf5 format. Here's where things stand right now (using the Tiny NIRSpec dataset processed through the Eureka Quickstart with all the defaults, with five spectral bins).  

```python
from chromatic import *
s3 = Rainbow('test-datasets/S3_wasp39b_ap6_bg7_SpecData.h5')
s3.normalize().imshow(vmin=0.98, vmax=1.02);
```

![image](https://user-images.githubusercontent.com/4691081/174960575-71ddf660-a6c5-400e-8523-867e8a82df13.png)

```python
s4 = Rainbow('test-datasets/S4_wasp39b_ap6_bg7_LCData.h5')
s4.normalize().imshow(vmin=0.98, vmax=1.02);
```

![image](https://user-images.githubusercontent.com/4691081/174960623-83706109-bf39-4b9e-a7e6-ae1499a02ddb.png)

```python
s5 = RainbowWithModel('test-datasets/S5_wasp39b_ap6_bg7_Table_Save_ch*.txt')
s5.imshow_data_with_models()
```

![image](https://user-images.githubusercontent.com/4691081/174960689-550172b0-76c9-4b00-be97-cd14f8c28cb1.png)

I have a few questions:
1. Have I covered all the main outputs that fall into the general category of "flux as a function of wavelength and time", or are there others I should be aware of?
2. Do you expect any major changes to these outputs soon? Right now, there's a little bit of flexibility to respond to new columns that might appear, but it's not perfect and it definitely won't handle structural changes. If there are big things coming soon, can someone please give me a heads up? For example, should I expect the `S5_*Table_Save_ch*.txt` files to change into some astraeus-based thing, or will the text files stick around for a while. 
3. Is there are difference between the `S3_*SpecData.h5` and `S4_*SpecData.h5` outputs? Right now they appear to be practically identical, but I'm guessing these might be different if the drift correction is being applied? It currently uses the same reader for both, so the main question is whether the files will ever have different structures. 
4. You should be able to try this out for yourselves as of version 0.2.3, which is the current version on the `develop` branch and also up on `pip`. I'd love if someone else could please try using it to load some of your own S3, S4, and/or S5 data, and let me know what what bugs you run into!

Thanks so much! Congrats on the submitted Eureka paper!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zkbt** [comment]
Oh, one more question!
5. Right now I haven't added `astraeus` as an official dependency for `chromatic`. I'm happy to do so, but I'd love to hear from some of your folks who've been playing with it more that you didn't run into any weird installation conflict issues by installing it. Am I probably safe to include it as a required dependency?

**Comment by taylorbell57** [comment]
1. I believe that is everything, yes. However, I notice that the Stage 3 figure does not have wavelength as a y-axis - is there something that stopped you from being able to do so?
2. We haven't talked recently about making any significant changes, but changing the csv files from Stage 5 and 6 to Astraeus save files is possible in the moderately near future. There will definitely be added columns, but that shouldn't bother your code at all. Hopefully the rest should be fairly stable though.
3. You raise a good point, I'm not sure why we copy that file in Stage 4 - currently there are no edits made to it, but it's possible @kevin218 copied it so that it's easier for users to decorrelate against something from that file in Stage 5.
4. Sounds good - I'm working on a plane today, but I can try to look at it tomorrow and others should as well.
5. I personally have had no issues installing it in the same environment as all of Eureka!'s other annoying dependencies, but that's a small sample size. It mostly depends on xarray which requires python >3.8 I believe.

**Comment by kevin218** [comment]
1. Is there also a function that includes a systematics panel, thus making it a 4-panel plot?  Can you manually specify min/max ranges using optional arguments?
2. Yeah, we'll probably move to Astraeus outputs fairly soon with S5.  Making the change on your end should be trivial.
3. I expect `spec` will be updated with the drift-corrected spectra, so I've left it as an output in S4.
5. I second Taylor's statement.  The python >3.8 requirement was the most annoying issue, if you could even call it that.  In general, Xarray is well supported by other scientific communities, so installation bugs are unlikely.

**Comment by zkbt** [comment]
Oh, and yet one more question:
6. Is it worth me writing Eureka writers in addition to the existing readers, at least for S3 and S4? That would allow us to, for instance, let you start from someone else's spectra or light curves to do your own fitting. Would creating `SpecData` and `LCData` files in your formats be enough for that, or are there other outputs that would be needed?

**Comment by taylorbell57** [comment]
Re `planet_model` and `systematics_model`, we currently don't separate those two out, but I think we have all the infrastructure setup so that it should be easy to separate those in the S5 output file.

For Q6, things are currently formatted such that Stages 4-6 require the MetaData save file from the previous stage, so a Eureka! writer at present wouldn't easily work for those stages. We definitely should work on making it easier for people to start using Eureka! from any stage though, and after some changes on our end I think it'd be great to have Eureka! writers.
