### ISSUE TITLE
Enable S3 to loop over multiple aperture sizes when specified in the .ecf file (intermediate).  Already implemented in POET, just need to replicate format.

### ISSUE THREAD

**Issue by kevin218** [kevin218/Eureka#40]

**Comment by kevin218** [comment]
In addition to giving a single value, it would be nice to be able to specify a range of aperture sizes (e.g., [min, max, stepsize]) in the .ecf file that the S3 pipeline can loop over.  The ecf reader can already handle lists, so that shouldn't be a problem.  Saving multiple results could be a challenge and we may want to create multiple sub-directories to handle each aperture size.

**Comment by kevin218** [comment]
We may also want to implement something similar with the background region, but let's take one step at a time.

**Comment by taylorbell57** [comment]
For me this currently breaks during the transition from S3 to S4 with or without multiple aperture sizes. Currently, the run_eureka.py file runs S3 and then S4 sequentially, and since the folder naming convention has changed, S4 can't find which *_Table_Save.txt file it is supposed to work on. For a single aperture, this could be remedied easily enough, but for multiple apertures it becomes unclear what the desired behaviour is: should S4 run over all the same apertures or only whichever was somehow preferred after S3? If it is the former, a glob search of *_Table_Save.txt files could be a clean way forward regardless of whether one or many apertures were considered.

**Comment by kevin218** [comment]
I like the idea of a glob search, but we should make sure to check for existing S4 outputs within a given directory to avoid overwriting the outputs. Maybe throw a warning in that case.
