### ISSUE TITLE
[Enhancement]: spectrophotometric lightcurves in ascii and/or csv format

### ISSUE THREAD

**Issue by trappist1i** [kevin218/Eureka#426]
### Instrument

Light curve fitting (Stages 4-6)

### What is your suggestion?

For those not accustomed to work with HDF files and willing to perform their own analyses of the light curves extracted in stage 4, it would good to have a simple output file in ascii or csv with as columns (e.g.): BJD_TDB (mid-exposure), Flux_ch1, Error_Flux_ch1, Flux_ch2, Error_Flux_ch2, etc + columns for the measured external parameters (background value, y-FWHM, drift in pixel, etc. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
We used to do this, but we no longer plan to have such an output. I understand your thought process that using xarray save files may require a little bit more learning to start using them, they are far faster to read in, they give much smaller files (because CSV-type files don't handle >2D data you end up duplicating a lot of values), and they give much more flexibility in the information that can be contained (can store units, can automatically track the connection between detector pixel index and wavelength, can add an essentially unlimited amount of extra ancilliary information potentially useful for decorrelation, etc.). And honestly, it isn't all that clear that xarray save files would indeed take more learning to use as with a CSV file you'd still have to figure out the column names, column units, column separators, and how to reshape the data back into a >2D array. Meanwhile there is only one way in which an xarray save file can be read in, and all of the work of understanding the loaded save file is greatly simplified by just doing something like

```
import xarray
filename = 'S4_miri_ap4_bg10_LCData.h5'
dataset = xarray.open_dataset(filename, engine='h5netcdf')
print(dataset)
```
