### ISSUE TITLE
Times in BJD_TDB 

### ISSUE THREAD

**Issue by trappist1i** [kevin218/Eureka#463]
### Instrument

Other (any stage)

### What is your suggestion?

I see that the measurement times written in the *LCdata.h5 output file of Stage 4 are the MJD_UTC of the start of the integration. It could be interesting to have them transformed to the BJD_TDB  of the mid-integration instead, as many users will use only Stage 1-4 of Eureka! and will then analyze the resulting light curves with different tools. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
The times from Stages 3+ save files are the "int_mid_BJD_TDB" values from the JWST FITS headers (should actually be called "int_mid_BMJD_TDB"). So that's the BMJD_TDB of mid-integration already which I believe is what you're asking for. HST is a bit trickier as that value is not stored just directly in the FITS header, but I'm pretty sure we've already implemented the code to covert the FITS times for HST to BMJD_TDB of the mid-integration.

Closing this issue for now as I believe what you're asking for is already implemented, but please reopen this if I have misunderstood something.
