### ISSUE TITLE
[Enhancement]: Suggestion for S5 binned-lightcurve

### ISSUE THREAD

**Issue by xueqiao** [kevin218/Eureka#467]
### Instrument

Light curve fitting (Stages 4-6)

### What is your suggestion?

Thank you so much for this super user-friendly JWST data analysis package!! 
1. In S6, when I try to plot the params(c0,c1 etc), I found it changes from negative to positive in fig6101 and in Table_Save.txt. I suggest changing `medians.append(np.abs(fitted_values["50th"][ind]))` in line350 in `s6_spectra.py` to `medians.append(fitted_values["50th"][ind])` 
2. I suggest to bin some data(like, add a line in S5 control file to let users input how many data be binned) in fig5101 like the figure below. Sometimes it's hard to tell whether it fitted well because many points are overlapped with each other.
![fig5101_ch01_lc_emcee](https://user-images.githubusercontent.com/73056170/193938739-cb193fb9-83d8-4a07-99b2-b32ff13184df.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
For your comment about Stage 6, can you clarifiy which version of Eureka! you are running (run `pip show eureka`)? I am pretty sure that bug has already been fixed in a newer version of Eureka! than you are using

Point well taken about binning for plotting purposes in Stage 5 - I did add a figure like that for phase curve observations as phase variations are basically impossible to see in unbinned data, but adding that feature to any type of obsevation would indeed be helpful

**Comment by xueqiao** [comment]
Thanks! Bugs fixed after update!
