### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by Aseman7** [kevin218/Eureka#500]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

I got this error in stage 2:

ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/asemon/src/eureka/Trappist1-NIRspec/Stage2/S2_2023-01-09_trappist1_run1/S2_trappist1.log' mode='w' encoding='UTF-8'>

how can I solve it?

Thanks 

### What operating system are you using?

Ubuntu (Linux-based)

### What version of Python are you running?

Python 3.9.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Hi, sorry for the very slow response - can you confirm that you are still having this issue? If so, can you copy-paste the whole traceback of the error message (and not just the last line of the error message) so I can understand where in the code this happened and why? My best guess at the moment is that the code was killed because the code tried to exceed your RAM size (jwst's Stage 1 and 2 pipelines are very RAM intensive unfortunately). Without more contextual information though I can't confirm that hypothesis or help you resolve the issue

**Comment by Aseman7** [comment]
Thanks for your message and for your time. Now, I don't have this problem. I close that.
