### ISSUE TITLE
Install issue on M1 processor

### ISSUE THREAD

**Issue by Tusay** [kevin218/Eureka#574]
### What happened?

I'm trying to install Eureka on my work mac. I'm following the instructions to clone the git and install from the yml file, but when I do it gives me this:

Collecting package metadata (repodata.json): done
Solving environment: - 

I left it on "Solving environment" overnight and it was still spinning its wheel the next day. It is currently still going...
I don't think it should take this long and I fear it is hung in some kind of infinite loop. 

I'm happy to be wrong and will update if it resolves itself eventually, in which case this may serve as a reminder to others with the same issue to be patient. 

Otherwise, I don't know how to resolve this. I haven't tried the other install method since I am using an M1 chip and the install guide makes it clear that trying the other way is unlikely to work.

### What operating system are you using?

Mac OS 12.6.7 Monterey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
It definitely shouldn't take more than a few minutes to find a solution.  Are you working in a clean conda environment?

**Comment by taylorbell57** [comment]
Thanks for posting this issue here. This is a new one for me and I really don't expect this is something caused by an issue on our end and is more likely to be an issue with your conda setup and/or internet access. It's not unusual for the `Solving environment` step to take a minute or few, but definitely shouldn't take hours. If I were in your position, I'd try to troubleshoot this by making a new conda environment yourself with some assorted packages (e.g. `conda create -n testEnv python==3.9.7 numpy[version='>=1.20.0,<1.22'] matplotlib scipy astropy`) which will not be sufficient for running Eureka! but will allow you to see whether you have broader issues with your conda installation (e.g. does a simpler conda environment that has nothing to do with Eureka! also fail to solve). You might also want to check that you have the `conda-forge` channel enabled on your conda install (which you can do with `conda config --add channels conda-forge`) as that might help find versions compatible with your operating system

**Comment by Tusay** [comment]
@kevin218 The install instructions have me building a fresh conda environment from the yml file on git, which is what I'm trying to do.

@taylorbell57 I am able to create a new conda environment with all the packages you listed in your response. I also have a few separate environments that I've built so I know I'm able to build environments. I tried enabling the conda-forge channel (though I think I already had it enabled) and tried running it again. Same result.

To clarify, I'm using the install instructions [here](https://eurekadocs.readthedocs.io/en/latest/installation.html) and effectively all I've done to this point is clone the github repo, cd into the directory and try to install the new environment with the yml file:
git clone -b v0.9 https://github.com/kevin218/Eureka.git
cd Eureka
conda env create --file environment.yml --force

And that is where the wheel spins forever...

**Comment by taylorbell57** [comment]
@Tusay, can you instead try installing the code that is on the main branch (it has been far too long since we released another version number and I wonder if this is something that was fixed since v0.9). To do that, instead of cloning the v0.9 branch do `git clone -b main https://github.com/kevin218/Eureka.git` and then proceed with the rest of the instructions

**Comment by prunecamille** [comment]
Hi, @Tusay I've had **exactly** the same issue for a week now, on an M2 chip! So don't worry, you're not alone haha.
@taylorbell57 I just tried this and it seems to be working for me! Thank you so much.

**Comment by taylorbell57** [comment]
Thanks for letting me know! @kevin218, alright all the more reason to do a v0.10 ASAP. I'll double-check that the upgraded `jwst` version still works for all three instruments and then will open a PR which will also increment the Eureka! version number. We'll keep this issue open as a reminder to do that

**Comment by taylorbell57** [comment]
Reopening this for now as per my message above
