### ISSUE TITLE
NIRSpec G395H tilt event compensation when producing light curve for WASP39-b observation 

### ISSUE THREAD

**Issue by kohhei315** [kevin218/Eureka#669]
### Instrument

Light curve fitting (Stages 4-6)

### What happened?

I am currently working on the reproduction of light curve for WASP39-b in stage 4. Although I am setting the recordDrift and correctDrift to True, I keep getting a transit light curve that includes the tilt event. I am aware that the specific setting within parameters for drift correction of 1d spectra is causing this issue. However, I am not exactly sure of specific value to set for each parameters.

### What operating system are you using?

macOS Sonoma 14.5

### What version of Python are you running?

Python 3.11.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
I recommend against using correctDrift in Stage 4. This will not remove the tilt event. Instead, you should fit for it in Stage 5.

**Comment by taylorbell57** [comment]
Kevin is right, you should instead fit for the tilt event in Stage 5. I gave some guidance on how to deal with the mirror tilt event in the NIRSpec G395H transit observation of WASP-39b in a workbook I made for the [2023 Sagan Summer Workshop](https://nexsci.caltech.edu/workshop/2023/handson.shtml#II).  The most relevant notebook for you is the "Hands-on Session II: Fitting JWST Data: From Light Curves to Planet Spectra" which you can learn how to download and run in [this instruction guide](https://nexsci.caltech.edu/workshop/2023/SSW2023_Google_Colab_Instructions_updated.pdf). I strongly recommend you first try working on that notebook so that you can learn from it (you'll learn much more from working through the notebook rather than just reading a solution), but we did also publish my solutions [here](https://nexsci.caltech.edu/workshop/2023/SSW2023_Solution_Notebooks_updated.pdf).

I'll close this issue now since that workbook should be all that you need, but this does remind me that I need to add links to those Sagan Summer Workshop notebooks from our Eureka! documentation pages.

**Comment by kohhei315** [comment]
Thank you for your advice and providing me a hands-on notebook for Eureka! pipeline. It will definitely help me use Eureka! pipeline and understand the meaning of each parameters for further application.
