### ISSUE TITLE
wavelength range setting

### ISSUE THREAD

**Issue by Aseman7** [kevin218/Eureka#722]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

In my NIRSpec data reduction, I set wave_min = 0.6 microns and wave_max = 5.0 microns in S4.ecf to capture the H-alpha line around 0.65 microns. However, in the output files (S4_XXX_ap6_bg7_SpecData.h5 and S3_XXX_ap6_bg7_SpecData.h5), the wavelength data starts at 0.68 microns instead of the specified 0.6 microns. 

Interestingly, the plot file fig2101_file1_x1dints.png includes data slightly below 0.68 microns, closer to my wave_min.

What might be causing the .h5 output to start at 0.68 microns instead of 0.6?
Are there settings I can adjust to capture the 0.65-micron range in the output files?
Thank you so much.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
As would've been printed to the terminal when running Stage 4 and can also be seen in the log file output in Stage 4, the code tells you that it cannot go to as short a wavelength as you requested and that you'll need to adjust the first value in your `xwindow` parameter in Stage 3 to a smaller number in order to access those shorter wavelengths. I don't know precisely what value you should use, so you'll need to experiment a bit

**Comment by taylorbell57** [comment]
Assuming you're working on NIRSpec/PRISM, setting `xwindow` in Stage 3 to `[14,495]` should hopefully be broad enough to give you access to all the wavelengths you were wanting to access
